### ISSUE TITLE
movement_gravity is modified

### ISSUE THREAD

**Issue by SmallJoker** [Foghrye4/minetest_saturn#1]
[Chat log for reference](http://irc.minetest.net/minetest/2017-05-28#i_4946475)

Saturn seems to override the setting `movement_gravity` to allow floating in the space. But also other subgames will be affected by this minetest.conf change, thus `set_physics_override` would be a more elegant way.
```Lua
minetest.register_on_joinplayer(function(player)
	player:set_physics_override({
		gravity = 0 -- factor for the gravity value in `minetest.conf`
	})
end)
```

**Comment by Foghrye4** [comment]
Could you create a PR?

**Comment by Foghrye4** [comment]
Well, you fixed it. Probably. Thanks.
