### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by BrunoMine** [Foghrye4/minetest_saturn#3]
This project does not contain any method for contribute or backlog list. Is discontinued?

**Comment by Foghrye4** [comment]
Yes.

**Comment by BrunoMine** [comment]
I really was willing to start helping you with this project. Its concept is very innovative

**Comment by Foghrye4** [comment]
@BrunoMine you still can fork this project and create PRs. Any PRs will be merged without checks and questions.

**Comment by BrunoMine** [comment]
So you think someday in the future you can go back to developing it?

**Comment by Foghrye4** [comment]
@BrunoMine well, also you could create your own thread with your fork on Minetest forums.
I don't think I ever will return to Minetest.

**Comment by BrunoMine** [comment]
okay, thank you
